import 'package:firebase_auth/firebase_auth.dart'; // FirebaseAuthException for error parsing
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_text_styles.dart';
import '../application/auth_providers.dart';
import '../data/firebase_auth_service.dart';
import '../../../shared/models/user_roles.dart';

// ConsumerStatefulWidget: needs local state (controllers, loading) + Riverpod (providers)
class LoginScreen extends ConsumerStatefulWidget {
  const LoginScreen({super.key});
  @override
  ConsumerState<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends ConsumerState<LoginScreen> {
  final _formKey = GlobalKey<FormState>();
  final _emailCtrl = TextEditingController(); // Holds email field text
  final _passwordCtrl = TextEditingController(); // Holds password field text
  bool _obscurePassword = true; // Toggles password visibility
  bool _isLoading = false;

  @override
  void dispose() {
    _emailCtrl.dispose();
    _passwordCtrl
        .dispose(); // Always dispose controllers to prevent memory leaks
    super.dispose();
  }

  String? _validateEmail(String? value) {
    if (value == null || value.trim().isEmpty) return 'Email is required';
    final emailRegex = RegExp(
      r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
    );
    if (!emailRegex.hasMatch(value.trim()))
      return 'Enter a valid email address';
    return null;
  }

  String? _validatePassword(String? value) {
    if (value == null || value.isEmpty) return 'Password is required';
    return null;
    // No length check on login — user may have an older short password  // Only sign-up enforces min length
  }

  Future<void> _onSubmit() async {
    if (!_formKey.currentState!.validate())
      return; // Client-side validation first

    setState(() => _isLoading = true);
    final notifier = ref.watch(
      loginProvider.notifier,
    ); // loginNotifierProvider generated by build_runner
    final appUser = await notifier.signIn(
      email: _emailCtrl.text.trim(),
      password: _passwordCtrl.text,
    );
    if (!mounted) return;
    setState(() => _isLoading = false);

    if (appUser == null) {
      final error = ref.read(loginProvider); // Read the AsyncError state
      final message =
          error.whenOrNull(
            error: (err, _) => err is FirebaseAuthException
                ? FirebaseAuthService.parseError(err as FirebaseAuthException)
                : err.toString(),
          ) ??
          'Sign-in failed. Please try again.';
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(message),
          backgroundColor: Colors.red.shade700,
          behavior: SnackBarBehavior.floating,
        ),
      );
      return;
    }

    // Route based on role — same pattern as sign-up (Day 7)
    switch (appUser.role) {
      case UserRole.instructor:
        context.go('/instructor-home');
        break; // Instructor → instructor shell
      case UserRole.student:
      default:
        context.go(
          '/student-home',
        ); // Student (and any unknown role) → student shell
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Log In')),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Header
                Text('Welcome back', style: AppTextStyles.h1),
                const SizedBox(height: 8),
                Text(
                  'Log in to continue learning.',
                  style: AppTextStyles.bodyMedium,
                ),
                const SizedBox(height: 32),

                // Email field
                Text('Email Address', style: AppTextStyles.labelMedium),
                const SizedBox(height: 8),
                TextFormField(
                  controller: _emailCtrl,
                  validator: _validateEmail,
                  keyboardType: TextInputType.emailAddress,
                  autocorrect: false,
                  decoration: const InputDecoration(
                    hintText: 'you@example.com',
                    prefixIcon: Icon(Icons.email_outlined),
                  ),
                ),
                const SizedBox(height: 20),

                // Password field with visibility toggle
                Text('Password', style: AppTextStyles.labelMedium),
                const SizedBox(height: 8),
                TextFormField(
                  controller: _passwordCtrl,
                  validator: _validatePassword,
                  obscureText:
                      _obscurePassword, // Hides/shows password characters
                  decoration: InputDecoration(
                    hintText: 'Enter your password',
                    prefixIcon: const Icon(Icons.lock_outline),
                    suffixIcon: IconButton(
                      icon: Icon(
                        _obscurePassword
                            ? Icons.visibility_off_outlined
                            : Icons.visibility_outlined,
                      ),
                      onPressed: () => setState(
                        () => _obscurePassword = !_obscurePassword,
                      ), // Toggles visibility, triggers rebuild
                    ),
                  ),
                ),
                const SizedBox(height: 8),

                // Forgot password link (stub — wired Day 67)
                Align(
                  alignment: Alignment.centerRight,
                  child: TextButton(
                    onPressed: () {},
                    child: const Text('Forgot password?'),
                  ), // TODO Day 67: open reset password screen
                ),
                const SizedBox(height: 24),

                // Login button
                ElevatedButton(
                  onPressed: _isLoading ? null : _onSubmit,
                  child: _isLoading
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Text('Log In'),
                ),
                const SizedBox(height: 16),

                // Sign up link
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      'Don’t have an account?',
                      style: AppTextStyles.bodySmall,
                    ),
                    TextButton(
                      onPressed: () => context.go('/signup'),
                      child: const Text('Sign up'),
                    ), // Navigates to sign-up screen
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}



/*import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../application/auth_providers.dart';
import '../data/firebase_auth_service.dart';
import '../../../shared/models/user_roles.dart';

class LoginScreen extends ConsumerStatefulWidget {
  const LoginScreen({super.key});

  @override
  ConsumerState<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends ConsumerState<LoginScreen> {
  final _formKey = GlobalKey<FormState>();
  final _emailCtrl = TextEditingController();
  final _passwordCtrl = TextEditingController();
  bool _obscurePassword = true;

  @override
  void dispose() {
    _emailCtrl.dispose();
    _passwordCtrl.dispose();
    super.dispose();
  }

  // ── Validators ──────────────────────────────────────────────────────────────
  String? _validateEmail(String? value) {
    if (value == null || value.trim().isEmpty) return 'Email is required';
    final emailRegex = RegExp(
      r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
    );
    if (!emailRegex.hasMatch(value.trim())) {
      return 'Enter a valid email address';
    }
    return null;
  }

  String? _validatePassword(String? value) {
    if (value == null || value.isEmpty) return 'Password is required';
    return null;
  }

  // ── Submit ──────────────────────────────────────────────────────────────────
  Future<void> _onSubmit() async {
    if (!_formKey.currentState!.validate()) return;

    // ref.watch in build() keeps loginProvider alive during the Firebase call.
    // Navigation and errors are handled by ref.listen below.
    await ref
        .read(loginProvider.notifier)
        .signIn(email: _emailCtrl.text.trim(), password: _passwordCtrl.text);
  }

  // ── Build ───────────────────────────────────────────────────────────────────
  @override
  Widget build(BuildContext context) {
    // KEY FIX: ref.watch keeps the provider alive during the async Firebase call
    final loginState = ref.watch(loginProvider);
    final isLoading = loginState is AsyncLoading;

    // React to state changes → navigate on success, SnackBar on error
    ref.listen<AsyncValue<void>>(loginProvider, (previous, next) {
      // Only react when transitioning out of loading
      if (previous is! AsyncLoading) return;

      next.whenOrNull(
        data: (_) {
          // Use activeRole to decide which home screen to go to
          final appUser = ref.read(loginProvider);
          final activeRole = appUser != null
              ? (appUser as dynamic).activeRole as String?
              : null;

          if (activeRole == 'instructor') {
            context.go('/instructor-home');
          } else {
            context.go('/student-home');
          }
        },
        error: (err, _) {
          final message = err is FirebaseAuthException
              ? FirebaseAuthService.parseError(err)
              : err.toString();
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(message),
              backgroundColor: Colors.red.shade700,
              behavior: SnackBarBehavior.floating,
            ),
          );
        },
      );
    });

    return Scaffold(
      appBar: AppBar(title: const Text('Log In')),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // ── Header ────────────────────────────────────────────────────
                Text('Welcome back', style: AppTextStyles.h1),
                const SizedBox(height: 8),
                Text(
                  'Log in to continue learning.',
                  style: AppTextStyles.bodyMedium,
                ),
                const SizedBox(height: 32),

                // ── Email ─────────────────────────────────────────────────────
                Text('Email Address', style: AppTextStyles.labelMedium),
                const SizedBox(height: 8),
                TextFormField(
                  controller: _emailCtrl,
                  validator: _validateEmail,
                  keyboardType: TextInputType.emailAddress,
                  autocorrect: false,
                  decoration: const InputDecoration(
                    hintText: 'you@example.com',
                    prefixIcon: Icon(Icons.email_outlined),
                  ),
                ),
                const SizedBox(height: 20),

                // ── Password ──────────────────────────────────────────────────
                Text('Password', style: AppTextStyles.labelMedium),
                const SizedBox(height: 8),
                TextFormField(
                  controller: _passwordCtrl,
                  validator: _validatePassword,
                  obscureText: _obscurePassword,
                  decoration: InputDecoration(
                    hintText: 'Enter your password',
                    prefixIcon: const Icon(Icons.lock_outline),
                    suffixIcon: IconButton(
                      icon: Icon(
                        _obscurePassword
                            ? Icons.visibility_off_outlined
                            : Icons.visibility_outlined,
                      ),
                      onPressed: () =>
                          setState(() => _obscurePassword = !_obscurePassword),
                    ),
                  ),
                ),
                const SizedBox(height: 8),

                // ── Forgot password ───────────────────────────────────────────
                Align(
                  alignment: Alignment.centerRight,
                  child: TextButton(
                    onPressed: () {},
                    child: const Text('Forgot password?'),
                  ),
                ),
                const SizedBox(height: 24),

                // ── Login button ──────────────────────────────────────────────
                ElevatedButton(
                  onPressed: isLoading ? null : _onSubmit,
                  child: isLoading
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Text('Log In'),
                ),
                const SizedBox(height: 16),

                // ── Sign up link ──────────────────────────────────────────────
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      "Don't have an account?", // ← fixed apostrophe
                      style: AppTextStyles.bodySmall,
                    ),
                    TextButton(
                      onPressed: () => context.go('/signup'),
                      child: const Text('Sign up'),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
} // ← class closes HERE — _onSubmit and build must be INSIDE this brace
*/